export const courses = [
  {
    id: 1,
    title: 'The Ultimate Google Ads Training Course',
    category: 'Marketing',
    speaker: 'Jerome Bell',
    price: 100,
    image: 'jerome.jpg',
  },
  {
    id: 2,
    title: 'Prduct Management Fundamentals',
    category: 'Management',
    speaker: 'Marvin McKinney',
    price: 480,
    image: 'marvin.jpg',
  },
  {
    id: 3,
    title: 'HR  Management and Analytics',
    category: 'HR & Recruting',
    speaker: 'Leslie Alexander Li',
    price: 200,
    image: 'leslie.jpg',
  },
  {
    id: 4,
    title: 'Brand Management & PR Communications',
    category: 'Marketing',
    speaker: 'Kristin Watson',
    price: 530,
    image: 'kristin.jpg',
  },
  {
    id: 5,
    title: 'Graphic Design Basic',
    category: 'Design',
    speaker: 'Guy Hawkins',
    price: 500,
    image: 'hawkins.jpg',
  },
  {
    id: 6,
    title: 'Business Development Management',
    category: 'Management',
    speaker: 'Dianne Russell',
    price: 400,
    image: 'dianne.jpg',
  },
  {
    id: 7,
    title: 'Highload Software Architecture',
    category: 'Development',
    speaker: 'Brooklyn Simmons',
    price: 600,
    image: 'simmons.jpg',
  },
  {
    id: 8,
    title: 'Human Resources – Selection and Recruitment',
    category: 'HR & Recruting',
    speaker: 'Kathryn Murphy',
    price: 150,
    image: 'kathryn.jpg',
  },
  {
    id: 9,
    title: 'User Experience. Human-centered Design',
    category: 'Design',
    speaker: 'Cody Fisher',
    price: 240,
    image: 'cody.jpg',
  },
];
